name: Build/Publish Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ros-distro: [foxy, galactic, humble]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set SHORT_DATE env
      run: echo "SHORT_DATE=$(date +%y-%m-%d)" >> $GITHUB_ENV

    - name: Build and push (production)
      if: github.ref_name == 'main'
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64, linux/amd64
        build-args: ROS_DISTRO=${{ matrix.ros-distro }}
        push: true
        tags: |
          husarion/rviz2:${{ matrix.ros-distro }}
          husarion/rviz2:${{ matrix.ros-distro }}-${{ env.SHORT_DATE }}
        cache-from: type=registry,ref=husarion/rviz2:${{ matrix.ros-distro }}
        cache-to: type=inline

    - name: Build and push (testing)
      if: github.ref_name != 'main'
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64, linux/amd64
        build-args: ROS_DISTRO=${{ matrix.ros-distro }}-${{ github.head_ref || github.ref_name }} 
        push: true
        tags: husarion/rviz2:${{ matrix.ros-distro }}
        cache-from: type=registry,ref=husarion/rviz2:${{ matrix.ros-distro }}-${{ github.head_ref || github.ref_name }} 
        cache-to: type=inline