name: Build/Publish Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros-distro: humble
            platforms: "linux/amd64, linux/arm64"
          - ros-distro: galactic
            platforms: "linux/amd64, linux/arm64"
          - ros-distro: foxy
            platforms: "linux/amd64, linux/arm64"

    steps:

    - name: Print event name
      run: echo "Event name ${{ github.event_name }}"

    - name: Print branch name
      run: echo ${{ github.ref_name}}

    - name: Set SHORT_DATE env
      run: echo "SHORT_DATE=$(date +%y-%m-%d)" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (production)
      if: github.ref_name == 'main' && github.event_name == 'workflow_dispatch'
      uses: docker/build-push-action@v2
      with:
        platforms: ${{ matrix.platforms }}
        push: true
        build-args: |
          ROS_DISTRO=${{ matrix.ros-distro }}
        tags: |
          husarion/rviz2:${{ matrix.ros-distro }}
          husarion/rviz2:${{ matrix.ros-distro }}-${{ env.SHORT_DATE }}

    - name: Build and push (latest only)
      if: github.ref_name == 'main' && github.event_name != 'workflow_dispatch'
      uses: docker/build-push-action@v2
      with:
        platforms: ${{ matrix.platforms }}
        push: true
        build-args: |
          ROS_DISTRO=${{ matrix.ros-distro }}
        tags: husarion/rviz2:${{ matrix.ros-distro }}

    - name: Build and push (development)
      if: github.ref_name != 'main'
      uses: docker/build-push-action@v2
      with:
        platforms: ${{ matrix.platforms }}
        push: true
        build-args: |
          ROS_DISTRO=${{ matrix.ros-distro }}
        tags: husarion/rviz2:${{ matrix.ros-distro }}-${{ github.head_ref || github.ref_name }}